{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2b4c883c-109e-4baf-9440-1cb2b71a0edd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-09 12:51:20.752 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.690 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Vijay Kumar\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-01-09 12:51:21.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.690 \n",
      "`st.cache` is deprecated and will be removed soon. Please use one of Streamlit's new\n",
      "caching commands, `st.cache_data` or `st.cache_resource`. More information\n",
      "[in our docs](https://docs.streamlit.io/develop/concepts/architecture/caching).\n",
      "\n",
      "**Note**: The behavior of `st.cache` was updated in Streamlit 1.36 to the new caching\n",
      "logic used by `st.cache_data` and `st.cache_resource`. This might lead to some problems\n",
      "or unexpected behavior in certain edge cases.\n",
      "\n",
      "2025-01-09 12:51:21.702 No runtime found, using MemoryCacheStorageManager\n",
      "2025-01-09 12:51:21.706 No runtime found, using MemoryCacheStorageManager\n",
      "2025-01-09 12:51:21.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.963 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.979 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.993 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:21.997 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.002 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.016 Session state does not function when running a script without `streamlit run`\n",
      "2025-01-09 12:51:22.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.023 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.024 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.025 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.027 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.037 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.039 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.044 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.070 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-09 12:51:22.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "from tensorflow.keras.models import load_model\n",
    "\n",
    "# Function to load the trained model\n",
    "@st.cache\n",
    "def load_trained_model():\n",
    "    try:\n",
    "        model = load_model(\"multiclass_classifier.keras\")  # Replace with your model file path\n",
    "        return model\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error loading the model. Ensure the 'multiclass_classifier.keras' file exists: {e}\")\n",
    "        st.stop()  # Stop execution if the model is not loaded\n",
    "\n",
    "# Load the model\n",
    "model = load_trained_model()\n",
    "\n",
    "# Streamlit app title and description\n",
    "st.title(\"Laterite Type Classifier\")\n",
    "st.write(\"Enter the feature values in the sidebar to classify the type of laterite.\")\n",
    "\n",
    "# Sidebar for input fields\n",
    "st.sidebar.header(\"Input Features\")\n",
    "Ds = st.sidebar.number_input(\"Ds (mm)\", min_value=0.0, max_value=20.0, value=5.0, step=0.1)\n",
    "UCS = st.sidebar.number_input(\"UCS (MPa)\", min_value=0.0, max_value=25.0, value=10.0, step=0.1)\n",
    "IS50 = st.sidebar.number_input(\"IS50 (MPa)\", min_value=0.0, max_value=3.5, value=1.0, step=0.01)\n",
    "TS = st.sidebar.number_input(\"TS (MPa)\", min_value=0.0, max_value=3.0, value=1.5, step=0.01)\n",
    "Pw = st.sidebar.number_input(\"Pw (kg/m³)\", min_value=1400, max_value=3200, value=2000, step=10)\n",
    "Di = st.sidebar.number_input(\"Di (mm)\", min_value=1.5, max_value=3.5, value=2.0, step=0.01)\n",
    "Mc = st.sidebar.number_input(\"Mc (%)\", min_value=1.5, max_value=5.0, value=3.0, step=0.01)\n",
    "RQD = st.sidebar.number_input(\"RQD (%)\", min_value=10, max_value=50, value=30, step=1)\n",
    "\n",
    "# Predict button\n",
    "if st.button(\"Classify\"):\n",
    "    try:\n",
    "        # Prepare input for prediction\n",
    "        input_features = np.array([[Ds, UCS, IS50, TS, Pw, Di, Mc, RQD]])\n",
    "        \n",
    "        # Make prediction\n",
    "        prediction = model.predict(input_features)\n",
    "        predicted_class = np.argmax(prediction)\n",
    "\n",
    "        # Map class index to Laterite Type\n",
    "        laterite_types = [\"ILT\", \"LT\", \"LTC\", \"LLT\"]\n",
    "        result = laterite_types[predicted_class]\n",
    "        \n",
    "        # Display results\n",
    "        st.subheader(\"Classification Result\")\n",
    "        st.write(f\"The predicted Laterite Type is: **{result}**\")\n",
    "        st.write(f\"Confidence: **{prediction[0][predicted_class]:.2f}**\")\n",
    "\n",
    "    except Exception as e:\n",
    "        st.error(f\"An error occurred during prediction: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a9147fcc-1fb3-4cd0-b801-af99600e160a",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "unexpected character after line continuation character (3022603636.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[4], line 1\u001b[1;36m\u001b[0m\n\u001b[1;33m    C:Users\\Vijay Kumar\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\u001b[0m\n\u001b[1;37m            ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m unexpected character after line continuation character\n"
     ]
    }
   ],
   "source": [
    " C:Users\\Vijay Kumar\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f185b1da-80a5-4d93-b4e1-15cba4b4f62e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
