{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6b32a576-1524-401b-acff-9a88a9eea676",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-11 16:47:47.033 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.036 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Vijay Kumar\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-01-11 16:47:48.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.046 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.058 Session state does not function when running a script without `streamlit run`\n",
      "2025-01-11 16:47:48.060 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.068 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.121 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.122 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.129 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.130 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.133 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.136 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.148 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.151 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.152 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.155 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.157 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.159 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.161 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.162 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:48.165 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.042 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.043 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.049 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.054 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-01-11 16:47:49.056 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import joblib\n",
    "\n",
    "# Load the pre-trained model\n",
    "model = tf.keras.models.load_model('ann_model.h5')\n",
    "\n",
    "# Streamlit app title\n",
    "st.title('Laterite Type Prediction')\n",
    "\n",
    "# Input fields for the user to enter the feature values\n",
    "st.sidebar.header('Enter the feature values')\n",
    "\n",
    "Ds = st.sidebar.number_input(\"Ds (Depth in meters)\", min_value=0.0, max_value=100.0, value=5.0)\n",
    "UCS = st.sidebar.number_input(\"UCS (Uniaxial Compressive Strength)\", min_value=0.0, max_value=100.0, value=10.0)\n",
    "IS50 = st.sidebar.number_input(\"IS50\", min_value=0.0, max_value=10.0, value=2.0)\n",
    "TS = st.sidebar.number_input(\"TS (Tensile Strength)\", min_value=0.0, max_value=10.0, value=1.5)\n",
    "Pw = st.sidebar.number_input(\"Pw (Weight of Particle)\", min_value=1000, max_value=5000, value=2500)\n",
    "Di = st.sidebar.number_input(\"Di (Density Index)\", min_value=1.0, max_value=5.0, value=2.0)\n",
    "Mc = st.sidebar.number_input(\"Mc (Moisture Content)\", min_value=1.0, max_value=5.0, value=2.5)\n",
    "RQD = st.sidebar.number_input(\"RQD (Rock Quality Designation)\", min_value=0, max_value=100, value=30)\n",
    "\n",
    "# Create a DataFrame from the input values\n",
    "input_data = pd.DataFrame({\n",
    "    'Ds': [Ds],\n",
    "    'UCS': [UCS],\n",
    "    'IS50': [IS50],\n",
    "    'TS': [TS],\n",
    "    'Pw': [Pw],\n",
    "    'Di': [Di],\n",
    "    'Mc': [Mc],\n",
    "    'RQD': [RQD]\n",
    "})\n",
    "\n",
    "# Load the scaler\n",
    "scaler = joblib.load('scaler.pkl')\n",
    "\n",
    "# Check the number of features expected by the scaler and model\n",
    "expected_features = scaler.mean_.shape[0]  # Number of features the scaler was trained on\n",
    "\n",
    "st.write(f\"Input data has {input_data.shape[1]} features.\")\n",
    "st.write(f\"Scaler expects {expected_features} features.\")\n",
    "\n",
    "# Standardize the input data only if the number of features is correct\n",
    "if input_data.shape[1] == expected_features:\n",
    "    # Standardize the input data\n",
    "    input_data_scaled = scaler.transform(input_data)\n",
    "\n",
    "    # Make prediction when the user clicks the button\n",
    "    if st.sidebar.button('Predict Laterite Type'):\n",
    "        # Make prediction using the trained model\n",
    "        prediction = model.predict(input_data_scaled)\n",
    "\n",
    "        # Get the class with the highest probability (argmax)\n",
    "        predicted_class = np.argmax(prediction, axis=1)[0]\n",
    "\n",
    "        # Define the possible classes (replace with your actual class names)\n",
    "        class_names = ['ILT', 'LT', 'LTC', 'LLT']  \n",
    "\n",
    "        # Display the result\n",
    "        st.write(f\"The predicted Laterite Type is: {class_names[predicted_class]}\")\n",
    "else:\n",
    "    st.error(f\"Mismatch in number of features. The model was trained with {expected_features} features, but the input data has {input_data.shape[1]} features.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "90555dbb-5c4f-426d-bed9-c4fdb05f0ba1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {},
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
